// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk62_q0UGnM7OVPi3pv_xt2h1ZtjxoXz8',
    appId: '1:876764974661:web:e342a937ca8e83d7251d2c',
    messagingSenderId: '876764974661',
    projectId: 'semesterproject-45943',
    authDomain: 'semesterproject-45943.firebaseapp.com',
    storageBucket: 'semesterproject-45943.firebasestorage.app',
    measurementId: 'G-VB4G2M2K3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB34wdqWG6bPEN_CkLN9l9PVNkTp9eE744',
    appId: '1:876764974661:android:4ee6e857e733e3fd251d2c',
    messagingSenderId: '876764974661',
    projectId: 'semesterproject-45943',
    storageBucket: 'semesterproject-45943.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD17Rw0PosE7oC9AVERf9GI6ThwntSGdqc',
    appId: '1:876764974661:ios:1dc45a89bd14a991251d2c',
    messagingSenderId: '876764974661',
    projectId: 'semesterproject-45943',
    storageBucket: 'semesterproject-45943.firebasestorage.app',
    iosBundleId: 'com.example.semproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD17Rw0PosE7oC9AVERf9GI6ThwntSGdqc',
    appId: '1:876764974661:ios:1dc45a89bd14a991251d2c',
    messagingSenderId: '876764974661',
    projectId: 'semesterproject-45943',
    storageBucket: 'semesterproject-45943.firebasestorage.app',
    iosBundleId: 'com.example.semproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk62_q0UGnM7OVPi3pv_xt2h1ZtjxoXz8',
    appId: '1:876764974661:web:e971c9fe59145752251d2c',
    messagingSenderId: '876764974661',
    projectId: 'semesterproject-45943',
    authDomain: 'semesterproject-45943.firebaseapp.com',
    storageBucket: 'semesterproject-45943.firebasestorage.app',
    measurementId: 'G-Z3356EZ675',
  );
}
